import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12
decorations = "Buttonless" 
opacity = 0.8
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"

#regular
size = 16
