gui:
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
  nerdFontsVersion: "3"
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    manualCommit: false
os:
  editPreset: nvim
promptToReturnFromSubprocess: false
