#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 10
yabai -m config window_shadow on

yabai -m signal --add event=window_created action="yabai -m space --balance"
yabai -m signal --add event=window_destroyed action="yabai -m space --balance"

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off

yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^LocalSend$" manage=off
yabai -m rule --add app="^Urban VPN Desktop$" manage=off

yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Notion Calendar$" manage=off

yabai -m rule --add app="^WezTerm$" space=2
yabai -m rule --add app="^Google Chrome$" space=1
yabai -m rule --add app="^Discord$" space=4
