#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xffff3c3c      # Fiery red glow (active)
	inactive_color=0xff1a0f1a    # Deep shadow purple (inactive)
)

borders "${options[@]}"
