# prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# mouse
set -g mouse on

# splits
bind | split-window -h
bind - split-window -v

# vim movements
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set index ot 1
set -g base-index 1
set -g pane-base-index 1

# reload config
bind r source-file ~/.tmux.conf \; display "reloaded"

# true color
set -g default-terminal "screen-256color"

# faster escape
set -sg escape-time 0
